package test.webservice.pay;

/**
 * Please modify this class to meet your needs This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.2.14 2024-04-10T16:52:28.904+08:00 Generated source version: 3.2.14
 */
public final class SIPAYDATASender_HTTPSPort_Client {

  private static final QName SERVICE_NAME = new QName("http://www.zhy.com/app/common_pay",
    "SI_PAYDATA_SenderService");

  private SIPAYDATASender_HTTPSPort_Client() {
  }

  public static void main(String args[]) throws Exception {
    URL wsdlURL = SIPAYDATASenderService.WSDL_LOCATION;
    if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
      File wsdlFile = new File(args[0]);
      try {
        if (wsdlFile.exists()) {
          wsdlURL = wsdlFile.toURI().toURL();
        } else {
          wsdlURL = new URL(args[0]);
        }
      } catch (MalformedURLException e) {
        e.printStackTrace();
      }
    }

    SIPAYDATASenderService ss = new SIPAYDATASenderService(wsdlURL, SERVICE_NAME);
    SIPAYDATASender port = ss.getHTTPSPort();

    {
      System.out.println("Invoking siPAYDATASender...");
      ZRFCCOMMONPAY _siPAYDATASender_parameters = null;
      ZRFCCOMMONPAYResponse _siPAYDATASender__return = port
        .siPAYDATASender(_siPAYDATASender_parameters);
      System.out.println("siPAYDATASender.result=" + _siPAYDATASender__return);

    }

    System.exit(0);
  }

}
