package test.webservice.pay;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.2.14 2024-04-10T16:52:28.947+08:00 Generated source version: 3.2.14
 */
@WebServiceClient(name = "SI_PAYDATA_SenderService",
  wsdlLocation = "http://wdqas01.zhouheiya.cn:50000/dir/wsdl?p=ic/d3cf132db0bf3494a3894a09d3bc82d0",
  targetNamespace = "http://www.zhy.com/app/common_pay")
public class SIPAYDATASenderService extends Service {

  public final static URL WSDL_LOCATION;

  public final static QName SERVICE = new QName("http://www.zhy.com/app/common_pay", "SI_PAYDATA_SenderService");
  public final static QName HTTPSPort = new QName("http://www.zhy.com/app/common_pay", "HTTPS_Port");
  public final static QName HTTPPort = new QName("http://www.zhy.com/app/common_pay", "HTTP_Port");

  static {
    URL url = null;
    try {
      url = new URL("http://wdqas01.zhouheiya.cn:50000/dir/wsdl?p=ic/d3cf132db0bf3494a3894a09d3bc82d0");
    } catch (MalformedURLException e) {
      java.util.logging.Logger.getLogger(SIPAYDATASenderService.class.getName())
        .log(java.util.logging.Level.INFO,
          "Can not initialize the default wsdl from {0}",
          "http://wdqas01.zhouheiya.cn:50000/dir/wsdl?p=ic/d3cf132db0bf3494a3894a09d3bc82d0");
    }
    WSDL_LOCATION = url;
  }

  public SIPAYDATASenderService(URL wsdlLocation) {
    super(wsdlLocation, SERVICE);
  }

  public SIPAYDATASenderService(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public SIPAYDATASenderService() {
    super(WSDL_LOCATION, SERVICE);
  }

  public SIPAYDATASenderService(WebServiceFeature... features) {
    super(WSDL_LOCATION, SERVICE, features);
  }

  public SIPAYDATASenderService(URL wsdlLocation, WebServiceFeature... features) {
    super(wsdlLocation, SERVICE, features);
  }

  public SIPAYDATASenderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
    super(wsdlLocation, serviceName, features);
  }

  /**
   * @return returns SIPAYDATASender
   */
  @WebEndpoint(name = "HTTPS_Port")
  public SIPAYDATASender getHTTPSPort() {
    return super.getPort(HTTPSPort, SIPAYDATASender.class);
  }

  /**
   * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the
   *                 <code>features</code> parameter will have their default values.
   * @return returns SIPAYDATASender
   */
  @WebEndpoint(name = "HTTPS_Port")
  public SIPAYDATASender getHTTPSPort(WebServiceFeature... features) {
    return super.getPort(HTTPSPort, SIPAYDATASender.class, features);
  }

  /**
   * @return returns SIPAYDATASender
   */
  @WebEndpoint(name = "HTTP_Port")
  public SIPAYDATASender getHTTPPort() {
    return super.getPort(HTTPPort, SIPAYDATASender.class);
  }

  /**
   * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the
   *                 <code>features</code> parameter will have their default values.
   * @return returns SIPAYDATASender
   */
  @WebEndpoint(name = "HTTP_Port")
  public SIPAYDATASender getHTTPPort(WebServiceFeature... features) {
    return super.getPort(HTTPPort, SIPAYDATASender.class, features);
  }

}
