package test.webservice.pay;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.14 2024-04-10T16:52:28.944+08:00 Generated source version: 3.2.14
 */
@WebService(targetNamespace = "http://www.zhy.com/app/common_pay", name = "SI_PAYDATA_Sender")
@XmlSeeAlso({ ObjectFactory.class })
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIPAYDATASender {

    @WebMethod(operationName = "SI_PAYDATA_Sender", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "ZRFC_COMMON_PAY.Response", targetNamespace = "urn:sap-com:document:sap:rfc:functions", partName = "parameters")
    public ZRFCCOMMONPAYResponse siPAYDATASender(
      @WebParam(partName = "parameters", name = "ZRFC_COMMON_PAY", targetNamespace = "urn:sap-com:document:sap:rfc:functions")
        ZRFCCOMMONPAY parameters
    );
}
