package test.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.14
 * 2024-04-10T13:53:25.332+08:00
 * Generated source version: 3.2.14
 *
 */
@WebService(targetNamespace = "http://www.zhy.com/pos/pos2crm_003", name = "SI_POS2CRM_003_Sender")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIPOS2CRM003Sender {

    @WebMethod(operationName = "SI_POS2CRM_003_Sender", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "ZRFC_TXN_RECHARGE_UNDO.Response", targetNamespace = "urn:sap-com:document:sap:rfc:functions", partName = "parameters")
    public ZRFCTXNRECHARGEUNDOResponse siPOS2CRM003Sender(
        @WebParam(partName = "parameters", name = "ZRFC_TXN_RECHARGE_UNDO", targetNamespace = "urn:sap-com:document:sap:rfc:functions")
        ZRFCTXNRECHARGEUNDO parameters
    );
}
