package test.webservice;

/**
 * Please modify this class to meet your needs This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.2.14
 * 2024-04-10T13:53:25.295+08:00
 * Generated source version: 3.2.14
 *
 */
public final class SIPOS2CRM003Sender_HTTPSPort_Client {

  private static final QName SERVICE_NAME = new QName("http://www.zhy.com/pos/pos2crm_003",
    "SI_POS2CRM_003_SenderService");

  private SIPOS2CRM003Sender_HTTPSPort_Client() {
  }

  public static void main(String args[]) throws Exception {
    URL wsdlURL = SIPOS2CRM003SenderService.WSDL_LOCATION;
    if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
      File wsdlFile = new File(args[0]);
      try {
        if (wsdlFile.exists()) {
          wsdlURL = wsdlFile.toURI().toURL();
        } else {
          wsdlURL = new URL(args[0]);
        }
      } catch (MalformedURLException e) {
        e.printStackTrace();
      }
    }

    SIPOS2CRM003SenderService ss = new SIPOS2CRM003SenderService(wsdlURL, SERVICE_NAME);
    SIPOS2CRM003Sender port = ss.getHTTPSPort();

    {
      System.out.println("Invoking siPOS2CRM003Sender...");
      ZRFCTXNRECHARGEUNDO _siPOS2CRM003Sender_parameters = null;
      ZRFCTXNRECHARGEUNDOResponse _siPOS2CRM003Sender__return = port
        .siPOS2CRM003Sender(_siPOS2CRM003Sender_parameters);
      System.out.println("siPOS2CRM003Sender.result=" + _siPOS2CRM003Sender__return);

    }

    System.exit(0);
  }

}
